### ISSUE TITLE
Resize emoji SVG images to be larger

### ISSUE THREAD

**Issue by dougfelt** [googlefonts/noto-emoji#136]
SVG images currently are 128x128 since that's the png image size, and originally they were intended for building a version of NotoColorEmoji using SVG for the glyphs.  Consider using a larger size to facilitate web use.

**Comment by behdad** [comment]
Does this matter? Isn't the SVG size nominal anyway?  I ask because I'm thinking of the path simplifier code we need to develop, and the absolute size becomes relevant there.  So, thinking of 128px still being the level of detail we should keep sounds reasonable.

**Comment by asturur** [comment]
so often on web the svgs are opened in image tags. and get rasterized by browser.

in that process width and height in the svg tag will define the size of details that will get rasterized.

you can keep viewbox at 0 0 128 128 and current path data and specify width and heigth as big as you want

**Comment by rsheeter** [comment]
viewBox != web size.
