### ISSUE TITLE
Using NotoColorEmoji.ttf as webfont

### ISSUE THREAD

**Issue by stryju** [googlefonts/noto-emoji#191]
I am having issues with using `NotoColorEmoji.ttf` as webfont (regular one works just fine).
Browsers (checked on latest Chrome and Firefox) always fall back to next font in stack, is there anything that I'm missing? Or are browsers not ready yet to support this kind of font?

**Comment by dougfelt** [comment]
@jungshik, can you link to/provide info on browser support for CBDT fonts?

**Comment by stryju** [comment]
example: https://imminent-jacket.glitch.me/

**Comment by dougfelt** [comment]
I only have access a Mac right now, and it is known that CBDT fonts don't work on Chrome/Mac, so I can't comment on this.

**Comment by stryju** [comment]
I've checked on Mac and Yocto+Wayland - both seem to be affected :(
Do you happen to know if there are any efforts to enable CBDT fonts on Chrome?

**Comment by dougfelt** [comment]
@jungshik will know.  I tried to find a comment he'd left on another thread (maybe not in this repo) about chrome support for various formats on various platforms, but haven't been able to find it.

**Comment by DeeDeeG** [comment]
Must be this comment: https://github.com/googlei18n/noto-emoji/issues/185#issuecomment-346492019.

**Comment by dougfelt** [comment]
Yes, that's the one I was thinking of.  Thanks!

**Comment by stryju** [comment]
hm, so https://chromium-review.googlesource.com/c/chromium/src/+/706248 seems like what I'm looking for

**Comment by rsheeter** [comment]
Color fonts are a bit of a mess; there are many formats and inconsistent support. Fixing this is out of scope for this repo.

I hope we see https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md as a path forward in future.
