### ISSUE TITLE
Binary font file for Noto Color Emoji seems to be broken past a certain commit

### ISSUE THREAD

**Issue by DeeDeeG** [googlefonts/noto-emoji#200]
Hi all. There seems to be an issue with the binary font.

Expected: Latest binary font checked into the repo (`fonts/NotoColorEmoji.ttf`) should be a working, usable font.

Actual: My system says it is corrupted and won't install it, browser won't use it in `@font-face`. This happens for the past three commits. That is, every commit in the history starting at (and including) https://github.com/googlei18n/noto-emoji/commit/ef89179e7de69445963bd93a8fcb02a15c929d61 and more recent: [`history for NotoColorEmoji.ttf`](https://github.com/googlei18n/noto-emoji/commits/master/fonts/NotoColorEmoji.ttf)

I am on Linux Mint, equivalent to Ubuntu 16.04

**Comment by komanaki** [comment]
Hey there,
I've got the same problem with Elementary OS 0.4.1, based on `Ubuntu 16.04.3 LTS`
The font file is "corrupted" according to the font manager starting from the exact same commit, ef89179.
Using the ttf file from the previous commit works perfectly though, on Chrome & Firefox for emoji display.

**Comment by george-chakhidze** [comment]
Windows 8.1/10 complains too. Definitely corrupted.

**Comment by DeeDeeG** [comment]
The past five revisions of the pre-compiled font all work for me at the moment.

I'm on Linux Mint 19 MATE edition, equivalent to Ubuntu 18.04

Unfortunately, it is a known issue that this font file isn't understood by Windows, which thinks it is broken. See issue #43.

**Comment by rsheeter** [comment]
The font should work anywhere that supports https://docs.microsoft.com/en-us/typography/opentype/spec/cbdt.

Closing as stale.
