### ISSUE TITLE
Please consider using gray or white for moon emoji

### ISSUE THREAD

**Issue by jbicha** [googlefonts/noto-emoji#206]
Especially at small sizes, it is hard to recognize that the 🌕 and 🌝 emoji are meant to represent the moon. Of the two, I think the smiling moon is the hardest to identify since it looks to me like a regular smiley.

I think it would help if the moon were represented as gray or white since it's the sun that's yellow not the moon! (Perhaps outlined so that it displays better on whiter backgrounds.)

References
----------------
https://emojipedia.org/full-moon-symbol/
https://emojipedia.org/full-moon-with-face/

**Comment by utack** [comment]
I have really gotten the moon from one person because if this, they thought it is a normal emoji

**Comment by jbicha** [comment]
There are several other [moon emoji](https://emojipedia.org/search/?q=moon). The other moon phases are more easily understandable despite their color.

**Comment by dougfelt** [comment]
Good point, this is a problem.  Thanks for bringing it to our attention.

**Comment by jbicha** [comment]
I think the moon is made out of white cheese not yellow. :rofl:

**Comment by sg3510** [comment]
We made the moon emoji have more visible craters to avoid the confusion:
https://emojipedia.org/full-moon-symbol/

**Comment by jbicha** [comment]
The Android 12 version is substantially improved in my opinion. A much paler yellow and prominent bloches of color for the craters. Thanks!

https://emojipedia.org/full-moon/
