### ISSUE TITLE
Help to build Notocoloremoji.ttf

### ISSUE THREAD

**Issue by mrsdbskn** [googlefonts/noto-emoji#220]
Hi all

I need some help to build a notocoloremoji.ttf file I extracted all IOS 11.3 Emojis from emojipedia.org and i would like to compile the png to an Notocoloremoji.ttf which works with OREO.

Do you guys can help me with that what I need beside the png files and how they have to be named they are (I named them like emoji_u1fxxxx). 

Do I need also .svg files from the emojis?

I would really appreciate it if someone could help me.

**Comment by dougfelt** [comment]
You don't need the .svg files, only png.

Regional flags are handled separately from the other emoji by the Makefile.  It expects them to be named by an ASCII representation of the region code, since that's how we get them from upstream.  If our flags are ok you can ignore this.

I don't recall precisely what tools are needed.  We might still require nototools for the build, as described in the README.  If you do you need to get it from googlei18n/nototools.  There are docker files under nototools that can build a complete environment but you might not need that to just build the emoji font.

Put all the emoji files in a single directory.  If you look at the emoji Makefile you'll see an EMOJI_SRC_DIR variable.  You can pass this on the makefile line and it will take the (non-flag) emoji from the dir you point at, e.g. 'make -j 4 EMOJI_SRC_DIR=/path/to/dir/containing/your/png/files'

Our default build uses the same image for several emoji sequences, for example most non-gendered sequences map to a gendered sequence.  These mappings are in the emoji_aliases file.  If you need different mappings you might need to edit this file first.

**Comment by mrsdbskn** [comment]
Thank you dougfelt I tried to build a Emoji font but failed...


C:\Users\miras\Desktop\noto-emoji-master>make -j 4 EMOJI_SRC_DIR=png\128
process_begin: CreateProcess(NULL, which zopflipng, ...) failed.
process_begin: CreateProcess(NULL, which optipng, ...) failed.
process_begin: CreateProcess(NULL, which add_vs_cmap.py, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
process_begin: CreateProcess(NULL, env python C:\Users\miras\Desktop\noto-emoji-master\flag_glyph_name.py AC AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG ER ES ET EU FI FJ FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MR MS MT MU MV MW MX MY MZ NA NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SX SY SZ TA TC TD TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UN US UY UZ VA VC VE VG VI VN VU WS YE ZA ZM ZW GB-ENG GB-SCT GB-WLS, ...) failed.
mkdir -p "build/emoji"
make -C third_party/pngquant
mkdir -p "build/quantized_pngs"
A subdirectory or file -p already exists.
mkdir -p "build/compressed_pngs"
Error occurred while processing: -p.
make[1]: Entering directory `C:/Users/miras/Desktop/noto-emoji-master/third_party/pngquant'
"using optipng"
./configure
A subdirectory or file -p already exists.
Error occurred while processing: -p.
process_begin: CreateProcess(NULL, env bash C:\Users\miras\Desktop\noto-emoji-master\third_party\pngquant\configure, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** No rule to make target `config.mk', needed by `lib/libimagequant.a'.  Stop.
make[1]: Leaving directory `C:/Users/miras/Desktop/noto-emoji-master/third_party/pngquant'
make: *** [third_party/pngquant/pngquant] Error 2
make: *** Waiting for unfinished jobs....
make: *** [build/quantized_pngs] Error 1
make: *** [build/compressed_pngs] Error 1

**Comment by dougfelt** [comment]
Knew there'd be something.  add_vs_cmap.py is in nototools.  The README mentions how to install it and make it available to your python system.

You might also want optipng, it looks like it can't find either that or zopflipng.  That will make the font smaller.

**Comment by mrsdbskn** [comment]
C:\Users\miras\Desktop\noto-emoji-master>make -j 4 EMOJI_SRC_DIR=png\120
process_begin: CreateProcess(NULL, which zopflipng, ...) failed.
process_begin: CreateProcess(NULL, which optipng, ...) failed.
process_begin: CreateProcess(NULL, which add_vs_cmap.py, ...) failed.
..........
..........
make -C third_party/pngquant
"using optipng "
make[1]: Entering directory `C:/Users/miras/Desktop/noto-emoji/third_party/pngquant'
./configure
process_begin: CreateProcess(NULL, env bash C:\Users\miras\Desktop\noto-emoji\third_party\pngquant\configure, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** No rule to make target `config.mk', needed by `lib/libimagequant.a'.  Stop.
make[1]: Leaving directory `C:/Users/miras/Desktop/noto-emoji/third_party/pngquant'
make: *** [third_party/pngquant/pngquant] Error 2
make: *** Waiting for unfinished jobs....
Invalid Parameter - 120x120
make: *** [build/emoji/emoji_u0023.png] Error 4
Invalid Parameter - 120x120
make: *** [build/emoji/emoji_u0023_20e3.png] Error 4


I had already installed nototools how it shows in the README but keep getting errors. All my png are 120x120 changed it also in the Makefile from noto-emoji.

**Comment by rsheeter** [comment]
Closing as stale.
