### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by scriby** [googlefonts/noto-emoji#222]
Firefox as of now only supports SVG-in-OpenType and COLR color font formats. It would be amazing to be able to use these emojis in FF as well.

Is there any potential to also generate one of those font formats as well? I would guess the SVG-based one would be easiest because SVG assets for the emojis already exist, but COLR would be nice as it would give Safari support as well.

Thanks for taking a look!

**Comment by scriby** [comment]
I played with this some today after noticing that it looks like a reasonable amount of effort has already gone into trying to build an OpenType SVG font.

After following instructions to setup noto-tools, I ran the following command to generate the SVG font:

`python generate_test_html.py NotoColorEmojiSvg.tmpl.ttx svg/emoji_u`

(I also had to tweak one call to add_image_glyphs that had an extra argument)

This output a NotoColorEmojiSvg.woff file and test html page (among other things). However, when opening the test HTML page (using a webserver, not file reference), it doesn't seem to work in FF. I debugged a bit and didn't see anything wrong with the test page itself and verified the font was getting loaded via the network tab, so I was wondering if something might be wrong with the font. Maybe my command to build the font was wrong?

**Comment by DeeDeeG** [comment]
I'm very interested in this, as a Firefox user.

Could you check the "Console" tab (`F12`) for errors? I've tended to see pretty helpful error messages when fonts don't load. Not always, but usually.

**Comment by scriby** [comment]
Nothing in the console.

I was able to open the font in FontLab. The characters looked a little funny, though. It appeared as if the glyphs were empty, but when opening an individual glyph I could see the content, but it seemed to be outside the visible area of the glyph.

It seems like even if that was the problem FF would just be showing blanks instead of falling back to the default emojis for the platform/browser. It seems more likely there's some problem with the character mapping, such that it's just not finding the glyphs at all for emojis.

**Comment by rsheeter** [comment]
The toolchain @ https://github.com/googlefonts/color-fonts may in time be able to build an SVG edition but I do not expect that to become a primary output for Noto Emoji.

The preferred long term solution to this is https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md. 

Closing because I don't expect further action in this repo.
