### ISSUE TITLE
The shirt on "Necktie" is semi-transparent!

### ISSUE THREAD

**Issue by gargoyle** [googlefonts/noto-emoji#224]
The main body of the short on the "Necktie" (U+1F454) emoji is semi transparent. This can be seen from the gnome-characters app which draws a baseline, and has a dark background on it's detail pop-up:-

![image](https://user-images.githubusercontent.com/437990/42717492-4e2a9c76-86f9-11e8-9926-4e808120ed89.png)
![image](https://user-images.githubusercontent.com/437990/42717497-5b51b16e-86f9-11e8-870b-7b9da3022a1c.png)

I don't think this is intentional as no other emoji seems to have any semi-transparent sections - not even the ghost! :-)

**Comment by dougfelt** [comment]
Looking into this.

**Comment by arjennienhuis** [comment]
See #232

**Comment by rsheeter** [comment]
Fixed in latest version (https://github.com/googlefonts/noto-emoji/blob/master/png/128/emoji_u1f454.png)
