### ISSUE TITLE
Adding Noto Color Emoji to Ubuntu's font stack breaks absolutely everything

### ISSUE THREAD

**Issue by NatoBoram** [googlefonts/noto-emoji#235]
With Noto Color Emoji : 

![image](https://user-images.githubusercontent.com/10495562/46579475-b4eba700-c9e0-11e8-95e1-16c6c6972527.png)

Without : 

![image](https://user-images.githubusercontent.com/10495562/46579490-02681400-c9e1-11e8-866d-eefcaacf29b6.png)

I'm currently trying to see Color Emojis in Firefox, Electron and Chrome, and, frankly, it's a pain in the ass. Electron doesn't seem to care *at all* about what I do, Chrome seems to be relatively unaffected, and Firefox reacts *only* to Noto Color Emoji... but seems to ignore *every single font* in the system when Noto Color Emoji is involved. I don't know where reports have to go anymore since *everything* doesn't work.

**Comment by NatoBoram** [comment]
I was using Ubuntu 18.10, and Ubuntu definitely doesn't support coloured emojis out of the box. I generally install Noto using [Font Manager](https://packages.ubuntu.com/bionic/graphics/font-manager) and the ZIP file. I'll see when I have the chance to reinstall if installing Noto from the package manager makes a difference.

**Comment by jbicha** [comment]
@NatoBoram Ubuntu 18.10 does support color emoji by default.

However, web browsers and web sites have different ways of handling emoji. (Also, LibreOffice and Qt apps are different.)

The font itself works so this is not the right place to report issues. You may need to report the issue to the specific web site that doesn't work or to the developers of the app you are using.

**Comment by rsheeter** [comment]
Closing as stale and possibly not the right place to pursue the issue.
