### ISSUE TITLE
Discoloured tongue on U+1F603

### ISSUE THREAD

**Issue by JoshyPHP** [googlefonts/noto-emoji#236]
The mouth's outline is visible through the tongue in U+1F603's artwork. Reordering the layers fixes the issue.

I'm attaching a screenshot of the original artwork and the fixed version for illustration, as the orange outline is hard to spot over a pink background at low resolutions.

![1f603](https://user-images.githubusercontent.com/317712/46966287-96a33c80-d0ad-11e8-95e6-0d86a6dd2f15.png)

**Comment by tomasdev** [comment]
No longer an issue.

https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f603.svg
https://github.com/googlefonts/noto-emoji/blob/master/png/128/emoji_u1f603.png
