### ISSUE TITLE
generate png images for Google Noto Color Emoji

### ISSUE THREAD

**Issue by harshal-shirude** [googlefonts/noto-emoji#237]
I want to use noto color emojis as an images (use image source url in `<img>`).
Can we generate 32x32 png noto color emoji images using this project? If yes, How?
I tried to execute `make`, but its giving below error:
```
/Library/Developer/CommandLineTools/usr/bin/make -C third_party/pngquant
./configure

  Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
     Cocoa: yes
    libpng: error ... not found (try: `brew install libpng`)

make[1]: *** No rule to make target `config.mk', needed by `lib/libimagequant.a'.  Stop.
make: *** [third_party/pngquant/pngquant] Error 2
```
Given that `libpng` is already installed.

**Comment by gregkepler** [comment]
Updating the pngquant library worked for me. PR #203 makes it a submodule which should do the trick.

**Comment by harshal-shirude** [comment]
Thanks @gregkepler. It unblocked me.

**Comment by harshal-shirude** [comment]
Getting 
```
waveflag.c:19:10: fatal error: 'cairo.h' file not found
```
I have cairo.h in `/usr/local/include/`.

**Comment by harshal-shirude** [comment]
Got it resolved. `pkg-config` was missing. Installed it using brew.

**Comment by rsheeter** [comment]
Closing as stale
