### ISSUE TITLE
can't generate NotoColorEmoji.ttf

### ISSUE THREAD

**Issue by GershonLin** [googlefonts/noto-emoji#238]
follow the README.md, i excute make -j4, but its giving below error:
'''
...
uchars = "".join ([unichr(cp) for cp in cps if not is_vs(cp)])
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
make: *** [Makefile:215: NotoColorEmoji.ttf] Error 1
'''
i modify emoji_builder.py, change unichr(i) to
'''
        def unichar(i):
        	try:
        		return unichr(i)
        	except ValueError:
        		return "".join(("\\U%08x" % i).decode('unicode-escape'))
'''
excute make again, fail with follow error:
'''
Traceback (most recent call last):
  File "third_party/color_emoji/emoji_builder.py", line 579, in <module>
    main (sys.argv)
  File "third_party/color_emoji/emoji_builder.py", line 525, in main
    glyph_name = get_glyph_name_from_gsub (uchars, font, unicode_cmap.cmap)
  File "third_party/color_emoji/emoji_builder.py", line 33, in get_glyph_name_from_gsub
    first_glyph = cmap_dict[ord (string[0])]
KeyError: 55356
make: *** [NotoColorEmoji.ttf] Error 1
'''
how can i successfully generte NotoColorEmoji.ttf?

**Comment by RoelN** [comment]
You need a "wide Python build". You can do this through [pyenv](https://github.com/pyenv/pyenv), for instance:

`PYTHON_CONFIGURE_OPTS="--enable-unicode=ucs4" pyenv install 2.7.16` 

And then use that version by executing `pyenv local 2.7.16` in the Noto Emoji directory before running `make`.

**Comment by RoelN** [comment]
Closing this as the codebase is Python3 now, which doesn’t have the narrow/wide build distinctions anymore.
