### ISSUE TITLE
Higher resolution PNG of at least 800x800px needed.

### ISSUE THREAD

**Issue by afurmanczyk** [googlefonts/noto-emoji#242]

**Comment by behdad** [comment]
What for?!

**Comment by afurmanczyk** [comment]
My use case is, bringing these emojis into a 4k premiere pro video sequence.

The problem, to my knowledge premiere pro doesn't support vector files ( AE does support vectors, but it's cumbersome to create comps every time I want to throw an emoji in.)

I'd like to be able to drag and drop in these emojis as high res PNGs. 

Looked for about 30 minutes on how to batch process them all, but kept hitting dead end solutions that wouldn't easily scale to 2,000 images.

**Comment by behdad** [comment]
Batch converting SVG to PNG is what you need indeed.

**Comment by afurmanczyk** [comment]
Yea, the closest thing I got was tried recording an action to run as batch on illustrator, but I had to sit there hitting enter twice for each image. If it was a  hundred images, no big deal, but for 2,000 it would take a few hours.

**Comment by behdad** [comment]
Use rsvg-convert from librsvg.

**Comment by asturur** [comment]
even a quick JS snippet is ok, i can share one.

**Comment by afurmanczyk** [comment]
I don't know what you guys are even saying. 😳

**Comment by rsheeter** [comment]
Unfortunately we will not be providing high-res pngs. I believe you should be able to produce them from the svgs.
