### ISSUE TITLE
Latest NotoColorEmoji.ttf (Aug 2018) doesn't support Android 6 or lower?

### ISSUE THREAD

**Issue by kawmra** [googlefonts/noto-emoji#243]
Hi

If I use the [latest NotoColorEmoji.ttf](https://github.com/googlei18n/noto-emoji/blob/4e5cf1ca8d9d38a2a9c72c284be5e3fba28cec87/fonts/NotoColorEmoji.ttf) under Android M, the application crashes.
But no probrem with Android N or higher.

Where can I check the Android version supported by NotoColorEmoji?

I think NotoColorEmoji.ttf that supports Unicode 10 distributed on [Google Noto Fonts site](https://www.google.com/get/noto/#emoji-zsye-color) was able to use with Kitkat or higher.

When I create `Typeface` instance:

```java
Typeface typeface = Typeface.createFromAsset(getAssets(), "fonts/NotoColorEmoji.ttf")
```

app crashes with this log:

```
E/Minikin: addFontFromAsset failed to create font fonts/NotoColorEmoji.ttf
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{[my package name]/[my activity class name]}: java.lang.RuntimeException: Font asset not found fonts/NotoColorEmoji.ttf
```

Thanks

**Comment by Sappurit** [comment]
Sorry to dig this old topic. I found out that Version 2.040;GOOG;noto-emoji:20231016:92a58ea6b2cfcad2560c2271855bc9c77eab6c51 works with KitKat now.
https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji-emojicompat.ttf
