### ISSUE TITLE
Android 9 new Emojis?

### ISSUE THREAD

**Issue by sabisab** [googlefonts/noto-emoji#244]
Adding android 9 Emojis? Their License?

**Comment by DeeDeeG** [comment]
I'm not a member of the developer team here...

But it appears the updated (Andoid 9) emoji were released as of this pull request: #225 

For the License info, see the README.md: https://github.com/googlei18n/noto-emoji#license

To summarize: 

I think the license is still the same as before. The [compiled fonts](https://github.com/googlei18n/noto-emoji/tree/master/fonts) are under [OFL](https://github.com/googlei18n/noto-emoji/blob/master/fonts/LICENSE).

And the code and images (PNGs and SVGs) are under [Apache](https://github.com/googlei18n/noto-emoji/blob/master/LICENSE).

Some flag SVGs are public domain or have whatever liberal license, and mostly appear to have been obtained from Wikimedia.

**Comment by rsheeter** [comment]
ac1703e9d7feebbf5443a986e08332b1e1c5afcf adds up to Emoji 12.1. License remains unchanged.
