### ISSUE TITLE
Unicode 12.0 (61 new emojis!)

### ISSUE THREAD

**Issue by forcemagic** [googlefonts/noto-emoji#251]
The Unicode standard version 12.0 has been around for about a month ([official summary](https://www.unicode.org/versions/Unicode12.0.0/), [emojipedia](https://emojipedia.org/emoji-12.0/)) and it introduced 61 new emojis.

Any release schedule/eta/info on supporting it? (I'd even help design them, but sadly I have no designing skills 😔)

**Comment by tramtrist** [comment]
Also looking forward to this update :)

**Comment by rsheeter** [comment]
Added in ac1703e9d7feebbf5443a986e08332b1e1c5afcf
