### ISSUE TITLE
Where to download noto emoji fonts

### ISSUE THREAD

**Issue by guoyunhe** [googlefonts/noto-emoji#254]
I have read https://www.google.com/get/noto/help/install/ where you can download a Noto-hinted.zip bundle containing Noto Emoji and Noto Color Emoji. But the font files are very old.

Should I download font files from this GitHub repo, or some better place?

Thanks!

**Comment by jungshik** [comment]
Noto color emoji is in a separate repo, https://github.com/googlefonts/noto-emoji .

**Comment by jacktose** [comment]
The built font files in this repo are 1 and 3 years old. The font files on the pretty, public-facing site are 3 years old or more. They're not listed at all on Google Fonts.

It seems this repo is semi-active, but is nobody using it? Does everyone build their own files? Where is a regular user supposed to get a file.

**Comment by rsheeter** [comment]
I have updated the emoji font, png, and svg assets for Unicode 13. Another option would be to grab the font from AOSP.
