### ISSUE TITLE
Meta table not found with EmojiCompat in Android

### ISSUE THREAD

**Issue by eygraber** [googlefonts/noto-emoji#268]
I built NotoColorEmoji.ttf using `make -j` but when I try to use it with EmojiCompat in Android it throws an Exception saying it could not read the metadata.

[This is where the meta tag is searched for](https://android.googlesource.com/platform/frameworks/support/+/refs/heads/androidx-master-dev/emoji/core/src/main/java/androidx/emoji/text/MetadataListReader.java#139).

**Comment by dougfelt** [comment]
Android doesn't use the font as-is built from this repo, they have their own tooling that reworks the font.  I expect the metadata is something they do, I have no involvement with that part of things.  You can try asking the Android folks.  I don't know if all their tooling for the font is available or documented.

**Comment by rsheeter** [comment]
The EmojiCompat font is a derivative of this one; see https://android.googlesource.com/platform/external/noto-fonts/+/refs/heads/master/emoji-compat/.
