### ISSUE TITLE
Some flags got broken

### ISSUE THREAD

**Issue by afranke** [googlefonts/noto-emoji#273]
Some flags have recently been broken, like the French one which has been replace by the one for the French Southern Territories. I think https://github.com/googlefonts/noto-emoji/commit/44f3e5b7f29f957a7fdc3b5f9d16e085d5e183c9#diff-9466bf003853e0af3a9d76b3f1f04575 contains the offending changes (NL affected too?).

**Comment by RoelN** [comment]
Thanks for reporting! Looks like this was fixed in 20756903e349d4b9dd1abfe35905ac94e7b45e89 👍
