### ISSUE TITLE
Wheelchair SVG mix-up

### ISSUE THREAD

**Issue by Pr0methean** [googlefonts/noto-emoji#275]
https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f468_1f3fe_200d_1f9bd.svg is a hand-pushed wheelchair and https://github.com/googlefonts/noto-emoji/blob/master/svg/emoji_u1f468_1f3fe_200d_1f9bc.svg is an electric wheelchair. The filenames indicate these ought to differ only in skin tone.

**Comment by sg3510** [comment]
The filenames are correct - 1F9BC refers to motorised wheelchair (https://emojipedia.org/motorized-wheelchair/) and 1F9BD is manual wheelchair (https://emojipedia.org/manual-wheelchair/). 

1f468 - refers to the gender being male
1f3fe - is the emoji modifier for Fitzpatrick Skin Type 5
