### ISSUE TITLE
Please tag Unicode 12 release

### ISSUE THREAD

**Issue by jbicha** [googlefonts/noto-emoji#280]
I [package](https://tracker.debian.org/pkg/fonts-noto-color-emoji) the Noto Emoji font for Ubuntu where it is the default color emoji font. We generally package this font from the git release tags. Although Android 10 was released a few weeks ago, there hasn't been a new release tag yet. Could you push a release tag soon?

**Comment by asturur** [comment]
i do not think is that straight forward.
I m not in the project tho.
Their master files needs to be converted to svg first.
They do not work directly on svg.

**Comment by jbicha** [comment]
@anthrotype Could you handle tagging this release or find someone who can? Thanks!

**Comment by anthrotype** [comment]
Yes, I will do that soon. If anybody would like to help me draft the release notes to put in the git tag message, that would be great :)

**Comment by asturur** [comment]
This release is for the font only or also for the SVG files?

**Comment by anthrotype** [comment]
good question. I don't know the history of those SVG files. @RoelN can you advise?

**Comment by asturur** [comment]
From my memory of talks happened in this repo, those fonts gets created from PNG that are exported from the source EPS files you work with to create the designs.

Sometimes you export those EPS in SVG, you clean up a bit and update the repo.

i know that the SVGs are not source of truth here for the font.
For me are extremely valuable since they represent a very cool clip art library without the resolution limit of PNGs

**Comment by RoelN** [comment]
All images should've been updated along with the font in https://github.com/googlefonts/noto-emoji/commit/31f714f349c340b2ed53983c9890aedd91ca2771 and https://github.com/googlefonts/noto-emoji/commit/61e91eee01af3a4a1383d1c731cdcbc8be189dec !

**Comment by asturur** [comment]
i remember pulling them down recently and did not really see them updated, but i ll double check the SVGs.

**Comment by asturur** [comment]
![image](https://user-images.githubusercontent.com/1194048/67297580-65442480-f4ea-11e9-9cb6-db3f4c2f049f.png)
yeah i see it now.

**Comment by dougfelt** [comment]
Fwiw, our process has been that the (non-flag) svg images are generated
from internal Adobe illustrator source files, and then cleaned up with
tooling. We don't hand patch the svg or the png files, since in the past
this has led to then getting out of sync with each other.

**Comment by jbicha** [comment]
> Yes, I will do that soon. If anybody would like to help me draft the release notes to put in the git tag message, that would be great :)

It looks like [release notes](https://github.com/googlefonts/noto-emoji/releases) have only rarely been used for this project. 😿

**Comment by anthrotype** [comment]
@jbicha tagged https://github.com/googlefonts/noto-emoji/releases/tag/v2019-11-19-unicode12
sorry for the delay
