### ISSUE TITLE
Remove Python 2.x support and add Python 3.x by default

### ISSUE THREAD

**Issue by bkdwt** [googlefonts/noto-emoji#287]
On systems like Gentoo you can't compile the noto-emoji package because it depends on Fonttools and Fontools has dropped the support for Python 2.x recently. 

Also, Python 2.x will have been removed on various Linux distros and has started being removed in various packages. So I think it is recommended to update the code and add support by default to Python 3.

**Comment by RoelN** [comment]
This repo has [recently](https://github.com/googlefonts/noto-emoji/releases/tag/v2019-11-19-unicode12) been updated to work with Python 3. Perhaps Gentoo needs to update the Noto Emoji package? Could you raise an issue there?

**Comment by PF4Public** [comment]
> Perhaps Gentoo needs to update the Noto Emoji package? Could you raise an issue there?

There's already one since 2019: https://bugs.gentoo.org/701702

**Comment by DeeDeeG** [comment]
Maybe reach out to the maintainer of the `noto-emoji` package directly?

See here for details: https://packages.gentoo.org/packages/media-fonts/noto-emoji

**Comment by PF4Public** [comment]
Or even mention him: @pacho2 :)

**Comment by DeeDeeG** [comment]
Can't hurt to try again... (Once, at least.)

---

Hi @pacho2,

I see you are listed as the maintainer for the `noto-emoji` package in Gentoo.

Would you be able to update the ebuild to the latest upstream code of Noto Emoji? Upstream has fixes related to the transition away from Python 2 toward Python 3, and user @bkdwt has posted an issue here in the upstram repo about it. (It appears the package is broken without these updates.)

Sorry to bother you, but reaching out to you seemed like the best way to move this issue forward.


Best Regards,

\- DeeDeeG

**Comment by PF4Public** [comment]
There is now new version available in Gentoo and it does have new emojis:
![image](https://user-images.githubusercontent.com/10319700/76707662-26657400-6702-11ea-9408-4708816d38b4.png)

So, I suppose, this bug could be closed…

**Comment by RoelN** [comment]
Thanks! :-)
