### ISSUE TITLE
Readme incorrectly states that NotoColorEmoji works on Windows

### ISSUE THREAD

**Issue by smarts** [googlefonts/noto-emoji#289]
I have Windows 10 version 1903 (which is more recent than the version that is supposed to support NotoColorEmoji, version 1607) and the NotoColorEmoji font still doesn't work.
`The file '…\NotoColorEmoji.ttf' does not appear to be a valid font.`
This has been an issue for years now and hasn't been fixed. Is this project/repository even active still?

**Comment by GiancarlosIO** [comment]
Yep, same here :(

**Comment by zac1st1k** [comment]
same

**Comment by tomasdev** [comment]
Duplicate of #43

**Comment by smarts** [comment]
@tomasdev this isn't a duplicate. THAT issue is about the font not working in Windows. THIS issue is about incorrect documentation.
