### ISSUE TITLE
Text vs Emoji presentation

### ISSUE THREAD

**Issue by darrnshn** [googlefonts/noto-emoji#290]
On Chrome OS (which uses Noto), certain emojis (e.g. ☺ "WHITE SMILING FACE") seem to default to text presentation. But if there's an emoji with emoji presentation in front of it, then it turns into emoji presentation too.

For example, this [emojipedia page](https://emojipedia.org/glossary/#text-presentation) renders the text presentation and the emoji presentation in the same way. It renders correctly on iOS Safari though.

Do we know why this is the case? Is this a font issue or a Chrome issue?

**Comment by ChiefMikeK** [comment]
Technically this is **not_an_emoji** it is a text/symbol character in the **"U+2600 - Miscellaneous Symbols"** block 
> Unicode® Technical Standard 51: https://unicode.org/Public/emoji/13.0/emoji-test.txt  
Fonts may or may _not_ support either or **_both_** text & emoji 💯

**Comment by dougfelt** [comment]
It seems reasonable to call any Unicode character with the Emoji property an "emoji".

U+263A has default text presentation.  It seems reasonable to expect it would get text presentation by default.  It depends on how ChromeOS assigns fonts to runs of text and how it controls variation selection within a font.  It's probably coalescing runs of these characters that it can get from the same font without examining their default presentation.

I don't think that currently a single Noto font contains both text and emoji presentations of characters (maybe old versions of Noto did, I don't remember).  So the system should be selecting which font to use based on the text, its unicode property data, and what the fonts tell it about the character/presentation they support.  Some systems tweak the Unicode default presentation though, for example I think Android changes some characters that Unicode defines as having default text presentation to default to emoji presentation instead.  At least this used to be true several years ago.

I suggesting raising with ChromeOS.

**Comment by darrnshn** [comment]
Thank you very much for the detailed explanation, that makes sense. I'll raise a bug on Chrome (OS).
