### ISSUE TITLE
"263A FE0F" is missing

### ISSUE THREAD

**Issue by guoyunhe** [googlefonts/noto-emoji#292]
```
263A FE0F                                  ; fully-qualified     # ☺️ E0.6 smiling face
```
Source: https://unicode.org/Public/emoji/13.0/emoji-test.txt

In Chromium:

![image](https://user-images.githubusercontent.com/5836790/76146728-f4b73200-609d-11ea-8fce-87e3f0be655b.png)

This is a fully qualified emoji ending with `FE0F`. So it shouldn't be override by other fonts.

**Comment by rsheeter** [comment]
Can you elaborate? How are you confirming this to be missing and in what context?

**Comment by guoyunhe** [comment]
Sorry, this was an issue with Liberation Serif font.
