### ISSUE TITLE
NotoColorEmoji.ttf wasn't updated in new release v2020-04-08-unicode12_1

### ISSUE THREAD

**Issue by guoyunhe** [googlefonts/noto-emoji#296]
The last update is 6 months ago.

**Comment by abcfy2** [comment]
Same issue. Please upgrade.

**Comment by Simon-Laux** [comment]
A github action that automatically builds attaches the build font files to the github release on tagging would be nice.

**Comment by rsheeter** [comment]
My mistake. I will update the font binary when adding emoji13.

**Comment by Safari77** [comment]
> My mistake. I will update the font binary when adding emoji13.

Now when I copy-paste 
🤲👐🙌👏🤝
from emojicopy.com to gnome-terminal, I get
![noto13](https://user-images.githubusercontent.com/3876865/88154744-89629c80-cc07-11ea-8f5c-8b8c8c1e6c26.png)

It works ok when I revert to the older ```NotoColorEmoji.ttf```.

**Comment by guoyunhe** [comment]
@Safari77 It works for me (Chromium on openSUSE with latest release today):

![图片](https://user-images.githubusercontent.com/5836790/88266474-f5acd100-ccd7-11ea-953c-7f640337d707.png)

**Comment by Safari77** [comment]
I wasn't talking about Chromium...

**Comment by guoyunhe** [comment]
@Safari77 then it is probably an issue of gnome-terminal. I am using KDE and all browsers and applications works fine:

![图片](https://user-images.githubusercontent.com/5836790/88365304-41ba4d00-cd8e-11ea-94aa-9b4b401613e7.png)

So it is not an issue of the the font itself but gnome-terminal doesn't support it.

**Comment by Safari77** [comment]
ttf fonts are supported ok, it's just that v12 works ok but with v13 all the emojis have shuffled places (to incorrect ones).

**Comment by coolreader18** [comment]
Yep, I have the same problem, Arch Linux with noto-fonts-emoji version 20200720-1 shows the emoji string "🐍😬📦" in the font preview as:
![noto color emoji regular: 🐎😭📦](https://user-images.githubusercontent.com/33094578/88709477-d00a3800-d0da-11ea-851f-6ed0f414a51d.png)

![noto color emoji italic: correct, italicized](https://user-images.githubusercontent.com/33094578/88709589-02b43080-d0db-11ea-8b3d-b2a148095f55.png)

![noto color emoji bold: 🐎😬📧](https://user-images.githubusercontent.com/33094578/88709622-0cd62f00-d0db-11ea-9255-cc0ef60b5abb.png)

![noto color emoji bold italic: correct, italicized](https://user-images.githubusercontent.com/33094578/88709815-4dce4380-d0db-11ea-8545-0aa68448167b.png)
