### ISSUE TITLE
Program

### ISSUE THREAD

**Issue by RickyBush** [googlefonts/noto-emoji#306]
Hey I was just wondering if you guys could make this into a program it will be so much better I keep on getting errors 😭

Also there should be an option to disable the image compress its taking way too long on my device 3hrs to two reuse 7 emoji_images 😭

An option just to replace the .png would be nice making the font from scratch all the time is a hassle 🤦‍♂️😭

I just say a program would just be awesome and easier for noobies like me 😂😂

**Comment by rsheeter** [comment]
I fear this repo will have to stay a full build for the forseeable future but you could explore using https://github.com/fonttools/fonttools to modify the font binary without having to compile from scratch.
