### ISSUE TITLE
"error" please help! 😭

### ISSUE THREAD

**Issue by RickyBush** [googlefonts/noto-emoji#307]
Keep getting this error after hours of waiting for it to make a font! 💀😭😭

I'm using Linux Ubuntu if that helps!

![IMG_20200603_112405](https://user-images.githubusercontent.com/44114154/83626046-ceb20880-a58c-11ea-9f4c-21693742267e.jpg)

**Comment by RickyBush** [comment]
Anyone else get this error? 😭😭😭

**Comment by RoelN** [comment]
The `check-virtual-env` string is not part of the Noto Emoji codebase. Any way your Makefile got messed up? Can you compare its contents to https://github.com/googlefonts/noto-emoji/blob/master/Makefile ?

**Comment by RickyBush** [comment]
Looks the same 😭

**Comment by RoelN** [comment]
@rsheeter Perhaps related to recent changes?

**Comment by anthrotype** [comment]
well, that "check-virtual-env" string is not coming from us.

here's a github-wide search for the string
https://github.com/search?q=check-virtual-env&type=Code

@RickyBush try to start afresh with a clean git clone of noto-emoji repository and see if that helps.

**Comment by RickyBush** [comment]
@anthrotype that done the trick thank you for your time! 💚
![Uploading IMG_20200604_212850.jpg…]()
