### ISSUE TITLE
🤔🤔🤔

### ISSUE THREAD

**Issue by RickyBush** [googlefonts/noto-emoji#308]
Would it be possible to just add .pngs to the existing font so I don't have to sit through this whole process like put the new .PNG in the compressed folder then skip straight to recompiling the font? I can't be waiting 5hrs each time to build a damn font! 💀😂😂

**Comment by m4rc1e** [comment]
Any reason why you can't just use the tagged releases?

**Comment by RickyBush** [comment]
What do you mean 😳

**Comment by m4rc1e** [comment]
We tag releases, https://github.com/googlefonts/noto-emoji/releases. Each release contains the generated fonts.

**Comment by RickyBush** [comment]
But I want to add my own .pngs 🤔

**Comment by RickyBush** [comment]
They're all name the same as the Google ones I just want to replace them I use to do with use using fonttools but I had to rename them all to the bitmap all the time so I was hoping I could use this tool just to add the .pngs then recompile the font 🤔
