### ISSUE TITLE
/bin/sh: 1: convert: not found

### ISSUE THREAD

**Issue by Daniyel33** [googlefonts/noto-emoji#311]
I get an error when triying to compile (make -j)

 
/bin/sh: 1: convert: not found  
/bin/sh: 1: convert: not found  
make: *** [Makefile:170: build/resized_flags/AC.png] Error 127  
make: *** Waiting for unfinished jobs....  
make: *** [Makefile:170: build/resized_flags/AD.png] Error 127  
/bin/sh: 1: convert: not found  
make: *** [Makefile:170: build/resized_flags/AE.png] Error 127  
/bin/sh: 1: convert: not found  
make: *** [Makefile:170: build/resized_flags/AF.png] Error 127  

I compile in Windows 10 (v1093) with Ubuntu from microsoft store

**Comment by graphicore** [comment]
I'm pretty sure it's the `convert` of the `imagemagick` package, so on Ubuntu I'd try:

```
$ sudo apt-get install imagemagick
```

Not sure how that works with Windows.

**Comment by RoelN** [comment]
Related: https://github.com/googlefonts/noto-emoji/issues/305
