### ISSUE TITLE
Fonts for emoji13 have emoji mixed up

### ISSUE THREAD

**Issue by coolreader18** [googlefonts/noto-emoji#314]
Coming from #296:

Arch Linux with noto-fonts-emoji version 20200720-1 shows the emoji string "🐍😬📦" in the font preview as:
![noto color emoji regular: 🐎😭📦](https://user-images.githubusercontent.com/33094578/88709477-d00a3800-d0da-11ea-851f-6ed0f414a51d.png)

![noto color emoji italic: correct, italicized](https://user-images.githubusercontent.com/33094578/88709589-02b43080-d0db-11ea-8b3d-b2a148095f55.png)

![noto color emoji bold: 🐎😬📧](https://user-images.githubusercontent.com/33094578/88709622-0cd62f00-d0db-11ea-9255-cc0ef60b5abb.png)

![noto color emoji bold italic: correct, italicized](https://user-images.githubusercontent.com/33094578/88709815-4dce4380-d0db-11ea-8545-0aa68448167b.png)

**Comment by DeeDeeG** [comment]
Is that Gnome Terminal or a different Terminal app?

**Comment by coolreader18** [comment]
It's `xfce4-terminal`

**Comment by DeeDeeG** [comment]
GNOME and Xfce both use GTK, maybe more shared components. So perhaps it's a GTK bug, or something like that.

**Comment by svito3** [comment]
Can't reproduce on Arch Linux, same font version.

Likely your font cache is corrupted, wipe user cache(just to be sure) and regenerate system cache:

```
rm -rf ~/.cache/fontconfig/
sudo fc-cache -r
```

**Comment by coolreader18** [comment]
Weird, it does seem fixed now -- even without refreshing the cache. Must've been some other update with some font rendering component.

**Comment by svito3** [comment]
You just needed to restart your terminal application then :+1:
