### ISSUE TITLE
Using gstatic URLs

### ISSUE THREAD

**Issue by nunoperalta** [googlefonts/noto-emoji#318]
Hello,

When using these URLs for Noto Emoji PNGs,

https://fonts.gstatic.com/s/e/notoemoji/latest/1f3f3_200d_26a7/128.png

Is there a way to replace "latest" with a snapshot of Unicode 13.0 ?

Also, there appears to be some PNGs that don't seem to be available through those URLs, yet they are generated when building the source code.

Two examples:

https://fonts.gstatic.com/s/e/notoemoji/latest/1f3fb/128.png

https://fonts.gstatic.com/s/e/notoemoji/latest/1f1e7/128.png

Any ideas why?
Thank you very much.

**Comment by tomasdev** [comment]
There's no versioning on gstatic currently.

The push to gstatic is now a bit outdated (Unicode 12.1) and I would personally recommend against using it, as it's not documented.

@rsheeter feel free to re-open if you'd like to push the 13.1 to gstatic.

**Comment by Mstrodl** [comment]
@rsheeter I would appreciate it if you could update the version on gstatic... Also it seems that while 1f3fb has been added, regional indicators are still missing for some reason... (1f1e7). I would be using the git repository, but that's missing the flags... Some guidance would be appreciated :)

A little looking around reveals that Google voice use their own copy, but that's only available in PNG form: https://www.gstatic.com/voice-fe/emoji/noto_v2/emoji_u1f1ed.png

**Comment by rsheeter** [comment]
fonts.gstatic should be up to 13.1. If naked region indicators are in RGI_Emoji (going from memory I believe not) then it's a bug if we don't support. Flags should be in https://github.com/googlefonts/noto-emoji/tree/main/third_party/region-flags.
