### ISSUE TITLE
Infinite recursion problem in Inkscape with SVGs of emoji 🌎 & 🏠

### ISSUE THREAD

**Issue by hcsch** [googlefonts/noto-emoji#321]
While playing around some with the SVG files of the emoji I noticed that for  [🌎 (U+1f30e)](https://github.com/googlefonts/noto-emoji/blob/352632eb1935fd2b732f6f3ca0a24e9754c3eccf/svg/emoji_u1f30e.svg?short_path=2de5132) and [🏠 (U+1f3e0)](https://github.com/googlefonts/noto-emoji/blob/7b180af3a60968383bba60e7384a246ab42d380b/svg/emoji_u1f3e0.svg?short_path=48318b9) Inkscape complains about exceeding some maximum iteration limit (`[...] More than 32 iteration while updating document [...]`).

The problem seems to be caused by a `radialGradient` tag inside of a group that references it by id for the `fill` attribute. There is an open issue about this in the Inkscape repository [here](https://gitlab.com/inkscape/inkscape/-/issues/1627). Going by what is mentioned in the issue, the `fill` referencing the `radialGradient` is inherited to the `radialGradient` tag, which causes some kind of self-referential-recursion.
This seems to be an issue which affects only Inkscape, other SVG renderers seem to be able to deal with this.

For [🌎 (U+1f30e)](https://github.com/googlefonts/noto-emoji/blob/352632eb1935fd2b732f6f3ca0a24e9754c3eccf/svg/emoji_u1f30e.svg?short_path=2de5132) the issue is with gradient `#a`, for [🏠 (U+1f3e0)](https://github.com/googlefonts/noto-emoji/blob/7b180af3a60968383bba60e7384a246ab42d380b/svg/emoji_u1f3e0.svg?short_path=48318b9) it's `#d`, moving these gradients out of the groups referencing them for their `fill` fixes the issue and doesn't affect the rendered result.

**Comment by frankrolf** [comment]
This seems to be fixed in the latest release.
