### ISSUE TITLE
The 13.1 NotoColorEmoji.ttf won't install on Windows

### ISSUE THREAD

**Issue by PeterCon** [googlefonts/noto-emoji#324]
When trying to install on Windows, it says it's an invalid font file.

**Comment by Titanic4** [comment]
There's Windows compatible version in the following location:
https://github.com/kabisa/noto-emoji/tree/windows-compat

**Comment by RoelN** [comment]
There's a PR waiting for re-review/merge here: https://github.com/googlefonts/noto-emoji/pull/323 (ping @anthrotype and @rsheeter :-)

@PeterCon You could try the binary from this PR here: https://github.com/kabisa/noto-emoji/blob/windows-compat/fonts/NotoColorEmoji_WindowsCompatible.ttf

**Comment by ChildishGiant** [comment]
That repo's down now, any other links?

**Comment by RoelN** [comment]
Agreed! :-)
