### ISSUE TITLE
Is attribution required for printed SVGs?

### ISSUE THREAD

**Issue by SvizelPritula** [googlefonts/noto-emoji#357]
I want to use some of the emojis in this font in a printed flier, however Scribus does not load this font properly. Therefore, I would have to import the SVGs directly.
With the OFL, I would not have to include attribution on my flier.
The SVGs are licensed under the Apache license, however, which suggests I would have to include a copy of the Apache license with my flier, which is ridiculous.

Since the SVGs are embeded into an OFL font, can I use them as if they were licensed under OFL?
If the scripts in this repo are apparently captable of turning Apache to OFL, could I just replace them with the cp command to get OFL licensed SVGs? How about if I extracted them from the ttf files?

**Comment by rsheeter** [comment]
@davelab6

**Comment by davelab6** [comment]
Yes, go ahead
