### ISSUE TITLE
Support for emojis in Unicode 14.0

### ISSUE THREAD

**Issue by nxcco** [googlefonts/noto-emoji#359]
Hi, is there any work yet done to support the emojis in the Unicode 14.0 draft?

**Comment by bege10** [comment]
The releases show the source for Unicode 14.0 but the downloadable font file seems to support only Unicode 12.1.
Would you, please, update the font file? Thank you very much.

**Comment by rsheeter** [comment]
AFAIK this is updated everywhere so closing.
