### ISSUE TITLE
COLRv1 version

### ISSUE THREAD

**Issue by o-t-w** [googlefonts/noto-emoji#370]
There is a COLRv1 version of this font used in this Codepen demo https://codepen.io/cssgrid/pen/xxLWPOe
Is this going to be made available?

**Comment by rsheeter** [comment]
That file is one of the COLRv1 builds in https://github.com/googlefonts/color-fonts. Specifically `fonts/noto-glyf_colr_1.ttf` (COLRv1 with outlines in the glyf table). We probably won't publish COLRv1 here until it's a bit more broadly usable.
