### ISSUE TITLE
Regex similar to Twemoji's

### ISSUE THREAD

**Issue by nunoperalta** [googlefonts/noto-emoji#380]
Is there a maintained "regex" that is compatible with your codepoints?
(or a way to generate one)

Something similar to this Twemoji's regex:
https://github.com/twitter/twemoji-parser/blob/master/src/lib/regex.js

I've been using Twemoji's regex to convert plaintext into Noto Emoji PNG, but there isn't support to 14.0 yet.
(and might not contain exactly the same amount of emoji as Noto Emoji)

	return String(str).replace(twemojiRegex, function (emoji) {
		var codepoint = emojiToCodePoint(emoji);
		...
		return '<img ...>';
	});

One good thing about it also, is that it's well "compressed" (reduces file size).

**Comment by tomasdev** [comment]
Not sure if any of these two work for you?

https://github.com/mathiasbynens/emoji-regex
And
https://github.com/googlefonts/emoji-metadata

**Comment by nunoperalta** [comment]
Thanks! The first one might help yeah - seems to be exactly what I'm looking for!!
Really appreciate that.
Cheers.
