### ISSUE TITLE
Must i give attribution even if I use single noto emoji for memes?

### ISSUE THREAD

**Issue by RuikangSun** [googlefonts/noto-emoji#382]
The license of noto emoji quite puzzled me. It seems that both Apache and SIL license apply for this project. If it is Apache licensed, technically I must give attribution even if I use noto emoji for memes. If SIL licensed, user are much easier to use.
So, as a normal user (insetad of developer or designer), how to fairly use noto emoji for personal use? For example, use noto emoji in video effect, memes creation.

**Comment by rsheeter** [comment]
Please see https://github.com/googlefonts/noto-emoji#license.

**Comment by twardoch** [comment]
Regarding the OFL, the [OFL FAQ](https://scripts.sil.org/ofl-faq_web) provides (not legally binding) explanation of the difference between distributing fonts and distributing documents that were created with the help of the fonts: 

»Question: 1.10 Does the full OFL license text always need to accompany the font?

Answer: The only situation in which an OFL font can be distributed without the text of the OFL (either in a separate file or in font metadata), is when a font is embedded in a document or bundled within a program. In the case of metadata included within a font, it is legally sufficient to include only a link to the text of the OFL on https://scripts.sil.org/OFL, but we strongly recommend against this. Most modern font formats include metadata fields that will accept the full OFL text, and full inclusion increases the likelihood that users will understand and properly apply the license.

Question: 1.11 What do you mean by 'embedding'? How does that differ from other means of distribution?

Answer: By 'embedding' we mean inclusion of the font in a document or file in a way that makes extraction (and redistribution) difficult or clearly discouraged. In many cases the names of embedded fonts might also not be obvious to those reading the document, the font data format might be altered, and only a subset of the font - only the glyphs required for the text - might be included. Any other means of delivering a font to another person is considered 'distribution', and needs to be accompanied by any copyright notices and licensing information available in OFL.txt.

Question: 1.12 So can I embed OFL fonts in my document?

Answer: Yes, either in full or a subset. The restrictions regarding font modification and redistribution do not apply, as the font is not intended for use outside the document.

Question: 1.13 Does embedding alter the license of the document itself?

Answer: No. Referencing or embedding an OFL font in any document does not change the license of the document itself. The requirement for fonts to remain under the OFL does not apply to any document created using the fonts and their derivatives. Similarly, creating any kind of graphic using a font under OFL does not make the resulting artwork subject to the OFL.«

— https://scripts.sil.org/ofl-faq_web

**Comment by twardoch** [comment]
I’m not a lawyer and what I write is not legal advice, but the common practice of understanding in the font community is that the »font« or »font software« is a piece of software that can be used to generate various texts that have some typographic appearance. 

My understanding of the OFL is: if you distribute a computer file that is a document, that is, it’s not a computer file that can be used to generate various texts, then you’re not distributing the font in the sense of hot the OFL sees it. 

Some people view a computer font to be a computer program. Then the text typeset with that font is the _output_ of the program, not the program itself. 

Again, I’m not a lawyer and what I had written is not legal advice, and I don’t represent Google in any way. But in 30 years of following licensing discussions, I haven’t heard any font maker requiring that documents credit the fonts used in them (except in very few cases where this has been clearly expressed in a proprietary EULA). 

I do wish that the actual text of the OFL were more explicit on that, but well, OFL is what we have.

**Comment by RuikangSun** [comment]
> 

Thank you so much! If the font itself is OFL instead of Apache licensed, I think it is much easier to use!
