### ISSUE TITLE
Off-artboard artwork for many SVGs

### ISSUE THREAD

**Issue by frankrolf** [googlefonts/noto-emoji#394]
I am working on a SVG-in-OT version of NotoEmoji, and I notice that many SVGs contain leftover artwork beyond the art board (or viewBox). For example, all the glyphs containing 1F485:
<img width="1604" alt="Screen Shot 2022-06-29 at 22 41 34" src="https://user-images.githubusercontent.com/2049645/176540742-6015ba14-89db-461d-b8ec-90b54adb6f15.png">
 
Using the SVG font, the result ends up looking like this:
<img width="1166" alt="Screen Shot 2022-06-29 at 22 42 50" src="https://user-images.githubusercontent.com/2049645/176540997-814d7b43-09fb-4905-afcc-1382cd5750ff.png">

I realize that cleaning up the SVGs might not be a high priority, but I would appreciate such work (rather than doing the same downstream on my end).
There must be a programmatic way to find outlines outside the view box, but unfortunately I have not found anything yet – pointers are welcome!

Thanks!

**Comment by anthrotype** [comment]
How do you run nanoemoji? The --clip_to_viewbox option should already be enabled by default, unless you set --noclip_to_viewbox CLI flag, or equivalent clip_to_viebox = false in the config.toml that your may feed nanoemoji.

**Comment by anthrotype** [comment]
Also maybe upload the source .SVG file and the exact command to reproduce, thank you!

**Comment by frankrolf** [comment]
I do use the raw .svg provided in this repo and wrap them into a SVG-in-OT font (repo and workflow here: https://github.com/adobe-fonts/noto-emoji-svg) 
At this moment I don’t use nanoemoji, but perhaps I could extract a method to understand how the clipping works.

**Comment by anthrotype** [comment]
Ah so you are _not_ using nanoemoji! I misunderstood then. The clipping happens in picosvg actually, nanoemoji simply calls picosvg with that option.

**Comment by anthrotype** [comment]
Sorry I was confused when I read the repository title "noto-emoji" I misread and thought you had posted this on the nanoemoji GitHub repo.. 😅

**Comment by frankrolf** [comment]
Thanks again for the pointers here!
For anyone reading this, the necessary command is `picosvg --clip_to_viewbox file.svg`
👍

**Comment by rsheeter** [comment]
Rather late +1 to use picosvg. My understanding is these surprising off-board assets are very helpful to the designers so we wouldn't want to alter the source.
