### ISSUE TITLE
☠️ Emoji Is Broken In Noto-COLRv1 Font

### ISSUE THREAD

**Issue by Sayhone721** [googlefonts/noto-emoji#400]
For some odd reason, the second bone behind the ☠️ emoji is **below** the skull. Also, for another odd reason, I can’t screenshot normally. And, I don’t even want to look at it myself!

**Comment by anthrotype** [comment]
Can you please be a bit more specific?

By "skull" emoji, you probably mean 💀 or U+1F480, right? => https://emojipedia.org/skull/

This is how [the Noto-COLRv1.ttf from this repository](https://github.com/googlefonts/noto-emoji/blob/main/fonts/Noto-COLRv1.ttf) looks to me on Chrome 104 on macOS:

<img width="149" alt="Screen Shot 2022-08-14 at 18 40 03" src="https://user-images.githubusercontent.com/6939968/184546532-0f572d39-2656-4319-90a8-2d623b406e2b.png">

The corresponding PNG file looks the same:
https://github.com/googlefonts/noto-emoji/blob/main/png/128/emoji_u1f480.png
![image](https://user-images.githubusercontent.com/6939968/184546688-19134bea-ac47-40a2-9c6c-ba9c9d76864b.png)

**Comment by Sayhone721** [comment]
I meant to say skull and crossbones. (☠️)

**Comment by anthrotype** [comment]
it looks good to me (Noto-COLRv1.ttf on Chrome 104 on macOS):
 
<img width="218" alt="Screen Shot 2022-08-15 at 09 47 11" src="https://user-images.githubusercontent.com/6939968/184596478-2a988915-6a49-47e4-8524-080f91aaec68.png">

below is the same emoji as PNG bitmap:
https://github.com/googlefonts/noto-emoji/blob/main/png/128/emoji_u2620.png
<img width="138" alt="Screen Shot 2022-08-15 at 09 47 24" src="https://user-images.githubusercontent.com/6939968/184596440-b10f9a94-6505-4786-9581-311c5b3a6e73.png">

You need to provide more information, e.g. what device, OS, browser name and version, a screenshot, anything

**Comment by Sayhone721** [comment]
I was on FontLab 8 trying to see the COLRv1 version. The “fact” that the ☠️ emoji is broken **must** be a FontLab 8 thing.

**Comment by anthrotype** [comment]
ok, thanks. Then I would suggerst you report the issue to FontLab. Closing as there's nothing to do on our end.

**Comment by Sayhone721** [comment]
Yep. This is a FontLab 8 thing.
![Screenshot (9)](https://user-images.githubusercontent.com/92538982/184645499-339e45f5-2108-4375-9606-ee1ae5cc5d15.png)
This is me on The FontGauntlet in Chrome.
