### ISSUE TITLE
Use of Google’s Noto Color Emojis in Documents, Photos and Videos Without License Text

### ISSUE THREAD

**Issue by ghost** [googlefonts/noto-emoji#403]
Hi! This question has been bothering me for a very long time and giving me a headache:

I would highly appreciate if someone could officially declare whether it would be fine to use the SVG and PNG files of Google's Noto Color Emoji Library for commercial purposes in for example documents, photos, videos and posters without adding the Apache license? Is attribution required in any form?

I'm curious as the Apache license, version 2.0 says "[...] 4. Redistribution. [...] (a) You must give any other recipients of the Work or Derivative Works a copy of this License; and (b) You must cause any modified files to carry prominent notices stating that You changed the files; [...]". The problem is that, for example, a poster on which the 11156-character license text would have to be included under each emoji would very quickly become very ugly. That's why I'm wondering if there is an official rule that Google and everyone involved agrees with?

That's about it. Thanks to the wonderful team that creates these great icons! Have a fantastic day!

**Comment by 1200lucas** [comment]
Could you give a final answer on this? @davelab6 
That would be fantastic. Thanks very much!
