### ISSUE TITLE
Prebuilt WOFF/WOFF2 files?

### ISSUE THREAD

**Issue by applecuckoo** [googlefonts/noto-emoji#407]
One of the big selling points of COLRv1 is the file size with compression, though ironically you don't offer any compressed builds. I'd like to self-host this font, but it seems that there aren't any WOFF or WOFF2 files in this repo. @rsheeter do you have a reason for this?

**Comment by rsheeter** [comment]
woff2 files for self-hosting can readily be produced for any font using https://github.com/google/woff2 or https://github.com/fonttools/fonttools.

**Comment by rsheeter** [comment]
I don't currently intend to add prebuilt woff files to this repo so closing.

**Comment by applecuckoo** [comment]
Cool, thanks for the quick reply!
