### ISSUE TITLE
Size of TTF in github and fonts.google.com?

### ISSUE THREAD

**Issue by djstrong** [googlefonts/noto-emoji#410]
What is the difference between files: [NotoColorEmoji.ttf](https://github.com/googlefonts/noto-emoji/blob/main/fonts/NotoColorEmoji.ttf) (10MB) and "Download family"
at https://fonts.google.com/noto/specimen/Noto+Color+Emoji (23MB)?

**Comment by idontveapc** [comment]
actually from the google fonts site it doesn't even work, only github's file works. maybe only on my handset!?

**Comment by rsheeter** [comment]
https://github.com/google/fonts/issues/5729#issuecomment-1464178963 outlines the fonts at play here.
