### ISSUE TITLE
"Surprised" emoji can't be downloaded as lottie/webp/gif

### ISSUE THREAD

**Issue by frederic-mamath** [googlefonts/noto-emoji#416]
# Expected behavior

- I can download the :surprised: emoji in gif/lottie or webp at: https://googlefonts.github.io/noto-emoji-animation/?icon.query=:surprised:

# Actual behavior

- Link seems to be broken and doesn't trigger any download unlike any other emojis

**Comment by belghitioth** [comment]
Good catch ! Hope that it will be fixed rapidly :)

**Comment by rsheeter** [comment]
Apologies for both the issue and slow response. I believe https://github.com/googlefonts/emoji-metadata mistakenly reported that emoji as animated. Fixed by https://github.com/googlefonts/emoji-metadata/pull/52.
