### ISSUE TITLE
[COLRv1] Can't build font

### ISSUE THREAD

**Issue by RadekBledowski** [googlefonts/noto-emoji#429]
I'm having trouble building colrv1 font.
What i did:
cloned main
First I've made new venv
installed requirements
did size check
and ran make command
moved built fonts to fonts folder
(I've skipped colrv1_generate_configs.py since there is no such file and it worked fine like some months ago to build font without it)
started " nanoemoji *.toml " and it keeps failing on "picosvg/clipped/emoji_u1f4fc.svg" or "picosvg/clipped/emoji_u1f4f0.svg" (it's random each time)

The problem started like month ago and still can't build font and i have no idea if that is problem with dependencies 
![Untitled](https://github.com/googlefonts/noto-emoji/assets/22264125/df1da278-7505-4abc-803d-5d8ac928f753)

Im on Ubuntu 22.04 LTS

**Comment by anthrotype** [comment]
See https://github.com/googlefonts/nanoemoji/issues/455 && https://github.com/googlefonts/picosvg/issues/304

Summary of above: this only now happens with skia-pathops 0.8.0, until this gets fixed in picosvg please keep skia-pathops pinned to the previous release `pip install skia-pathops==0.7.4`.

thanks

**Comment by RadekBledowski** [comment]
> See [googlefonts/nanoemoji#455](https://github.com/googlefonts/nanoemoji/issues/455) && [googlefonts/picosvg#304](https://github.com/googlefonts/picosvg/issues/304)
> 
> Summary of above: this only happens with skia-pathops 0.8.0, until this gets fixed in picosvg please keep skia-pathops pinned to the previous release `pip install skia-pathops==0.7.4`.
> 
> thanks

Thank you!!! This fixed the issue!
