### ISSUE TITLE
Add Bahá'í religion emoji for completeness on codepoint U+1F7D9

### ISSUE THREAD

**Issue by LaPingvino** [googlefonts/noto-emoji#431]
Tracking issue, might give it a try myself, and if rejected to figure out the correct procedure for this. Noto Sans Symbols 2 now has a normal character for this, but common usage of this will more likely be in emoji form.

The design can be simply the purple background of the other religions with the current Noto Sans Symbols 2 design star in the proper color inside it.

**Comment by jbicha** [comment]
There isn't yet a 9-point star representing Baháʼí in the official Unicode Emoji standard. It is not really appropriate for Google to add this unilaterally. Instead, it needs to be accepted by Unicode in a future Unicode standard.

See https://unicode.org/emoji/proposals.html

I found 2 older submissions that may need to be updated to comply with the current application process

- http://www.unicode.org/L2/L2017/17237-nine-pointed-star.pdf
- https://www.unicode.org/L2/L2020/20095-nine-pointed-star.pdf

**Comment by LaPingvino** [comment]
The last proposal went through and was a direct reaction to the first emoji proposal being refused. Do you have an example for how to update the standard properly? There doesn't seem to be a modern precedent for this.

On July 28, 2023 at 8:00 GMT, Jeremy Bicha ***@***.***> wrote:

There isn't yet a 9-point star representing Baháʼí in the official Unicode Emoji standard. It is not really appropriate for Google to add this unilaterally. Instead, it needs to be accepted by Unicode in a future Unicode standard.

See https://unicode.org/emoji/proposals.html

I found 2 older submissions that may need to be updated to comply with the current application process

- http://www.unicode.org/L2/L2017/17237-nine-pointed-star.pdf
- https://www.unicode.org/L2/L2020/20095-nine-pointed-star.pdf

**Comment by jbicha** [comment]
To be clear, I am not a (upstream) maintainer of Noto Emoji.

Congratulations on getting the Unicode codepoint. It is still not listed as an Emoji though.
https://unicode.org/emoji/charts/full-emoji-list.html#religion

I believe you are going to want to request that U+1F7D9 be given a emoji-default presentation in line with symbols for other religions. The alternative is text-default emoji presentation.

https://www.unicode.org/reports/tr51/#Presentation_Style

https://unicode.org/emoji/charts/text-style.html

I am guessing you or someone may need to go through the emoji proposal process again.

**Comment by LaPingvino** [comment]
Which existing document would be a good model for this?

**Comment by rsheeter** [comment]
I believe you would start at https://unicode.org/emoji/proposals.html. Even if they respond to say that's the wrong way to go about it they will probably know what the right way is :)

We would not update this repo until approved as an emoji by Unicode so I am closing here.

**Comment by LaPingvino** [comment]
That is where the proposal started at the time ;).
