### ISSUE TITLE
Request: Kurdistan flag

### ISSUE THREAD

**Issue by slashzanyar** [googlefonts/noto-emoji#436]
Hello, I request that the Kurdistan flag emoji be added.
About 85 million people need it.
If my request is approved, I am ready to do everything personally, including design.

More information about this flag:
[Other issues](https://github.com/Crissov/unicode-proposals/issues/117)
[emojipedia](https://emojipedia.org/flag-for-kurdistan-ir16)

**Comment by rsheeter** [comment]
I appreciate the offer to help. Unfortunately we do not support non-RGI flags. The presence of assets for non-RGI assets in the region flags of our third_party folder is potentially misleading. They don't make it into the final font even if the tool we use to fetch flags retrieves them.

**Comment by slashzanyar** [comment]
thanks. tell me more about RGI and Non-RGI Emojies

**Comment by anthrotype** [comment]
https://emojipedia.org/glossary#rgi
