### ISSUE TITLE
Can't find a Noto font that can show all Glyphs

### ISSUE THREAD

**Issue by davidgilbertson** [googlefonts/noto-emoji#437]
I would like a Noto font that can render any glyph, like a superset of all the Noto fonts.

I use Matplotlib in Python and that doesn't support character-level font family switching, so it seems that I can't actually use Noto even though all the individual fonts support the glyphs I need.

It seems odd that all this work goes into being able to display all these glyphs, but there isn't a single "Noto With The Lot" font that can do it all (I don't care if it's huge). Something akin to Segoe UI Emoji.

Does this exist and I haven't found it? Will this ever happen? Or is Noto only designed for systems that can do character-level font family fallback?

**Comment by rsheeter** [comment]
We have proposed changes to the font format to enable this, see https://github.com/harfbuzz/boring-expansion-spec. Specifically, the ability to have a pan-Unicode font is one of the reasons to want to break the 65k glyph limit as noted in https://rsheeter.github.io/more_gids.

Sadly that means for the time being there is no such font and we cannot readily create one.
