### ISSUE TITLE
broken chain is broken

### ISSUE THREAD

**Issue by idontveapc** [googlefonts/noto-emoji#442]
⛓️‍💥 vs 🔗‍💥 

one is working (first) and (second) one isn't. one combination doesn't have variation selector(vs)-16 (second one) and os broken.

combination:
1. ⛓️+️+‍+💥
2. 🔗+‍+💥

**Comment by Mercury13** [comment]
The first is intended to work. The second should not. Close?

**Comment by curya** [comment]
> second one is copied from emojipedia blog article about noto emoji update

https://blog.emojipedia.org/googles-emoji-15-1-support-in-noto-color-emoji/
This one?
I think that's a typo. If you click on it, it takes you to correct version.

**Comment by rsheeter** [comment]
Thank you for the report.

https://unicode.org/Public/emoji/15.1/emoji-test.txt lists two sequences for broken chain:

```
26D3 FE0F 200D 1F4A5                                   ; fully-qualified     # ⛓️‍💥 E15.1 broken chain
26D3 200D 1F4A5                                        ; unqualified         # ⛓‍💥 E15.1 broken chain
```

When I test each sequence against CBDT and COLRv1 builds of the font they seem to map both sequences to a single glyph, suggesting both sequences were recognized and produce the same output:

```shell
$ hb-shape --unicodes="26D3,200D,1F4A5" --ned fonts/Noto-COLRv1.ttf
[gid3488]
$ hb-shape --unicodes="26D3,FE0F,200D,1F4A5" --ned fonts/Noto-COLRv1.ttf
[gid3488]

$ hb-shape --unicodes="26D3,200D,1F4A5" --ned fonts/NotoColorEmoji.ttf
[gid1485]
$ hb-shape --unicodes="26D3,FE0F,200D,1F4A5" --ned fonts/NotoColorEmoji.ttf
[gid1485]
```

I think that means working as intended. If I misunderstood please reopen and clarify how to reproduce the problem.
