### ISSUE TITLE
NotoColorEmoji_WindowsCompatible.ttf is not... Windows compatible...

### ISSUE THREAD

**Issue by curya** [googlefonts/noto-emoji#443]
I tried installing the newest 15.1 font and it just doesn't work. It "installs" but it's like the font is empty or corrupt? No program recognizes it.

![image](https://github.com/googlefonts/noto-emoji/assets/71131343/82d92e9a-089a-4bfd-beff-f9e216b3e360)

**Comment by kenmcd** [comment]
The Microsoft Edge browser can display CBDT fonts like Noto Color Emoji.
From the front page of this repo...
> NotoColorEmoji uses the CBDT/CBLC color font format, which is supported by Android and Chrome/Chromium OS. Windows supports it starting with Windows 10 Anniversary Update in Chrome and Edge.

I am not aware of any other Windows applications that support CBDT fonts
Perhaps some graphics applications do.
Most common use of this font is on Android.

**Comment by curya** [comment]
You're right. I meant to make this about Noto-COLRv1.ttf. I'll close this and make another issue.
