### ISSUE TITLE
OpenType SVG fonts open slowly in Fedora 39 Linux

### ISSUE THREAD

**Issue by epico** [googlefonts/noto-emoji#452]
I downloaded the Noto Color Emoji fonts from Google website.
URL: https://fonts.google.com/noto/specimen/Noto+Color+Emoji?query=emoji

I check this font with ttx, it contains the SVG table inside the font.
`SVG   0x8EA0F1D5  19252109   4763880`
It seems this is an OpenType SVG font.

It takes several minutes to open this font with gnome-font-viewer.
I rebuilt ftview with librsvg, ftview also takes several minutes to open this font.

Why does it take several minutes to open the OpenType SVG font?

**Comment by anthrotype** [comment]
Well, quite simply because it's huge and the font viewer is probably trying to load all the thousands of emoji glyphs all at once. I'm not sure there is much we can do.

**Comment by rsheeter** [comment]
Ideally use the COLRv1 font (present in this repo under `/fonts`, see https://developer.chrome.com/blog/colrv1-fonts for context). That require that gnome-font-viewer and ftview support COLRv1; I'm not sure whether they do.

I don't think there is anything to be changed in this repo so closing.
