### ISSUE TITLE
Why is only the 👪  emoji not displayed?

### ISSUE THREAD

**Issue by nakagaw** [googlefonts/noto-emoji#453]
![image](https://github.com/googlefonts/noto-emoji/assets/6017747/5d96c1e5-7a91-49b0-bfa3-4ec01dd13b03)

Strangely, it's not a color icon even though it's included in JSON data.
😭 Please add 👪 emoji !!

**Comment by jbicha** [comment]
This was an intentional change in the Unicode Emoji recommendations.

More explanation at https://jenniferdaniel.substack.com/p/breaking-the-cycle#%C2%A7what-is-a-family

This has been adopted by other vendors. See https://emojipedia.org/family-adult-adult-child#designs for instance.

**Comment by nakagaw** [comment]
@jbicha Thank you reply, I understand the reason 😢

**Comment by jbicha** [comment]
If this issue is resolved for you, you can close it.

(I am just a community member and don't have access to close other people's issues.)
