### ISSUE TITLE
Build fails on Windows with mingw

### ISSUE THREAD

**Issue by foxypiratecove37350** [googlefonts/noto-emoji#456]
I'm tryng to build on Windows, with `mingw32-make`, and I started this command: `mingw32-make -j 48` (like the `make -j 48` in [`BUILD.md`](https://github.com/googlefonts/noto-emoji/tree/main/BUILD.md)), and I have this error:
```sh
make (e=206): Filename or extension too long.
mingw32-make: *** [check_sequence] Error 206
```
This is the total text outputed by the command (with in the command):
```sh
(venv) C:\Dcmt\noto-emoji>mingw32-make -j 48
process_begin: CreateProcess(NULL, which zopflipng, ...) failed.
process_begin: CreateProcess(NULL, which add_vs_cmap.py, ...) failed.
process_begin: CreateProcess(NULL, which ttx, ...) failed.
process_begin: CreateProcess(NULL, python3 check_emoji_sequences.py -n emoji_u270c.png [some emojis filname, ~94315 chars] emoji_u1fa7c.png emoji_u1f450_1f3ff.png emoji_u1f9d1_1f3fe_200d_1f9b2.png emoji_u1faf2_1f3ff.png emoji_u1f509.png emoji_u1f473_200d_2640.png emoji_u1f344.png emoji_u1f973.png emoji_u1f3c6.png emoji_u1f469.png -c, ...) failed.
make (e=206): Filename or extension too long.
mingw32-make: *** [check_sequence] Error 206
```

I hope you will help me.

**Comment by anthrotype** [comment]
Windows has limits on the length of paths. Maybe you could try to use the [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) (Windows Subsystem for Linux) to build Noto Emoji...

**Comment by foxypiratecove37350** [comment]
> Windows has limits on the length of paths. Maybe you could try to use the [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) (Windows Subsystem for Linux) to build Noto Emoji...

Ok, I will try with WSL and I will tell you if it work.

**Comment by foxypiratecove37350** [comment]
> Windows has limits on the length of paths. Maybe you could try to use the [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) (Windows Subsystem for Linux) to build Noto Emoji...

It seems work but also it seems have a new problem so I will open a new issue. Tell me if I have to close this issue or not.

**Comment by foxypiratecove37350** [comment]
> Windows has limits on the length of paths. Maybe you could try to use the [WSL](https://learn.microsoft.com/en-us/windows/wsl/about) (Windows Subsystem for Linux) to build Noto Emoji...

Here is the link of the issue for the new problem is you would: https://github.com/googlefonts/noto-emoji/issues/457.

**Comment by foxypiratecove37350** [comment]
> Unless there is a small tweak that would make it work I think we likely won't fix Windows builds so for now I will close and mark wontfix. Apologies for the inconvenience.

No problem, I tryied with WSL and it seems work (just there seems a little bit freeze but I create anew issue for this).
