### ISSUE TITLE
womanDancing and manDancing emojis are shown as the same

### ISSUE THREAD

**Issue by SimpleHK** [googlefonts/noto-emoji#462]
![image](https://github.com/googlefonts/noto-emoji/assets/44436877/07881a36-b9af-4f4d-bafb-73ab76166b42)
![image](https://github.com/googlefonts/noto-emoji/assets/44436877/982e45b0-ddcb-4594-822e-ff7fb3545a98)

**Comment by HaNerW10** [comment]
It is blob-human? so it is a non-gender.
