### ISSUE TITLE
Google fonts monochrome release missing 15.1?

### ISSUE THREAD

**Issue by forresto** [googlefonts/noto-emoji#464]
Related: upvote this issue: https://github.com/google/fonts/issues/7558 

---

I've noticed that [15.1 emoji](https://emojipedia.org/noto-emoji/15.1/new) that work in [color](https://fonts.google.com/noto/specimen/Noto+Color+Emoji?preview.text=%F0%9F%8D%8B%E2%80%8D%F0%9F%9F%A9%F0%9F%8D%84%E2%80%8D%F0%9F%9F%AB%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%A9%B9%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%94%A5):

![image](https://github.com/googlefonts/noto-emoji/assets/395307/c1efffa6-692c-4c01-9d5e-e9166058a9c0)

Don't work in [monochrome](https://fonts.google.com/noto/specimen/Noto+Emoji?preview.text=%F0%9F%8D%8B%E2%80%8D%F0%9F%9F%A9%F0%9F%8D%84%E2%80%8D%F0%9F%9F%AB%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%A9%B9%E2%9D%A4%EF%B8%8F%E2%80%8D%F0%9F%94%A5):

![image](https://github.com/googlefonts/noto-emoji/assets/395307/adf238d0-5e23-4f60-927d-0cd83afb80bd)

Is the Google fonts release behind?

Example [Noto Emoji v47 font link](https://fonts.gstatic.com/s/notoemoji/v47/bMrnmSyK7YY-MEu6aWjPDs-ar6uWaGWuob-r0jwvS-FGJCMY.ttf).

**Comment by bsoap-cat** [comment]
yea apparently it used to have it on September and it got removed a month later. I downloaded the font before noto b&w downgraded to 15.0

**Comment by forresto** [comment]
@bsoap-cat do you happen to have the 15.1 file? I'd like to poke it for my own experiments, and can't find that version.

**Comment by bsoap-cat** [comment]
here's the entire zip file if you want it
[Noto_Emoji.zip](https://github.com/googlefonts/noto-emoji/files/15046272/Noto_Emoji.zip)

**Comment by forresto** [comment]
Yes, thank you. That font file has version `3.002` whereas the version live on Google fonts now has `2.001`.

**Comment by forresto** [comment]
That font file (3.002) is missing these right-facing variations, which do exist in [Noto Color Emoji](https://fonts.google.com/noto/specimen/Noto+Color+Emoji?preview.text=👨%E2%80%8D🦯%E2%80%8D➡%EF%B8%8F👨%E2%80%8D🦼%E2%80%8D➡%EF%B8%8F👨%E2%80%8D🦽%E2%80%8D➡%EF%B8%8F👩%E2%80%8D🦯%E2%80%8D➡%EF%B8%8F👩%E2%80%8D🦼%E2%80%8D➡%EF%B8%8F👩%E2%80%8D🦽%E2%80%8D➡%EF%B8%8F🧑%E2%80%8D🦯%E2%80%8D➡%EF%B8%8F🧑%E2%80%8D🦼%E2%80%8D➡%EF%B8%8F🧑%E2%80%8D🦽%E2%80%8D➡%EF%B8%8F).

> 👨‍🦯‍➡️👨‍🦼‍➡️👨‍🦽‍➡️👩‍🦯‍➡️👩‍🦼‍➡️👩‍🦽‍➡️🧑‍🦯‍➡️🧑‍🦼‍➡️🧑‍🦽‍➡️

**Comment by wdymThisIsntAvailable** [comment]
The latest version of the font got re-added
[Link](https://fonts.google.com/noto/specimen/Noto+Emoji)

**Comment by rsheeter** [comment]
Apologies for the inconvenience, fixed along with https://github.com/google/fonts/issues/7558
