### ISSUE TITLE
Emoji 👪,👨‍👩‍👦,👨‍👩‍👧's Show Up SVGs

### ISSUE THREAD

**Issue by nataliakeniganti** [googlefonts/noto-emoji#475]
Hi, I seem to have a problem with noto color emoji. The "👪,👨‍👩‍👦,👨‍👩‍👧"'s in my program, Inkspace.
_This is a preview for the 👪._
![Zrzut ekranu 2024-07-21 105619](https://github.com/user-attachments/assets/1bddac7c-b8e9-41d6-85ff-5235ddcb87c1)

**Comment by RealityRipple** [comment]
This is not a bug. It's Emoji 15.1's definition of those family units. See https://www.unicode.org/L2/L2023/23029-family-emoji.pdf

**Comment by magda290** [comment]
> This is not a bug. It's Emoji 15.1's definition of those family units. See https://www.unicode.org/L2/L2023/23029-family-emoji.pdf

Emoji 15.1 Changed Family Emoji

**Comment by Mercury13** [comment]
Genderless family — yes. Family: man, woman, boy — changed to b/w too early, IMHO.

**Comment by Mercury13** [comment]
Sorry for writing false info, but now when Apple released these too, families are officially deprecated.
And even in deprecated characters Google made a nice twist: drew women’s haircuts.
