### ISSUE TITLE
Emoji Support For Windows 10

### ISSUE THREAD

**Issue by magda290** [googlefonts/noto-emoji#478]
Font Windows 10 22h2 Noto Emoji. Emoji 12.1, Emoji 13.0, Emoji 14.0, Emoji 15.0, Emoji, 15.1.

**Comment by magda290** [comment]
> Yes. Wednesday. Connectedness.

Yes Sure Font On Emoji Picker Windows 10.

**Comment by rsheeter** [comment]
We don't plan any specific work here so closing.

**Comment by nataliakeniganti** [comment]
> We don't plan any specific work here so closing.

COLRV1 Font

**Comment by nataliakeniganti** [comment]
mozzila firefox?

**Comment by kenmcd** [comment]
technical vegetables?
