### ISSUE TITLE
svg files contain a lot unneeded stuff

### ISSUE THREAD

**Issue by schriftgestalt** [googlefonts/noto-emoji#490]
this increases the file size quite a bit.

two examples:

there are a lot different versions:
![Image](https://github.com/user-attachments/assets/e193924f-724f-414d-9be4-f3d235f8a51d)
42KB vs 4KB

this contains a lot guide paths:
![Image](https://github.com/user-attachments/assets/77f1f358-c070-4ae5-a304-0ccf011e6fa5)
64KB vs 2 KB

**Comment by rsheeter** [comment]
I believe this is working as intended, the SVG files are captured as provided by design, we make no promise of any kind of optimization to their source form.
