### ISSUE TITLE
NotoColorEmoji.ttf is not a valid font on Mac

### ISSUE THREAD

**Issue by martin-gorner** [googlefonts/noto-emoji#72]
Double-clicking on the .ttf file opens FontBook but FontBook will not display the font.
The font cannot be used in any mac application even if installed in the Library/Fonts folder.
NotoEmoji-Regular.ttf works fine though.

**Comment by dougfelt** [comment]
MacOS does not support the color font format used in NotoColorEmoji, unfortunately, and currently we do not build a font in the format it supports.

**Comment by HiPhish** [comment]
I just tried importing the fonts into Font Book and there are two errors: `'sfnt' required` and `System Validaton` have the red X. Maybe someone will find that useful. I'm on OS X 10.11.6 (El Capitan).

**Comment by louisgardent** [comment]
@HiPhish Same on MacOS Sierra

**Comment by Crissov** [comment]
Should this issue really be titled something like _Provide an Apple-compatible font file using the `sbix` Opentype table_?

I tried to find another project that already did that, but so far without success. [Emojione provides fonts](https://github.com/Ranks/emojione/tree/master/extras/fonts) in several formats. I couldn't find one for [Twemoji](github.com/twitter/twemoji/) either. On the other hand, the community provides several [emoji font builds for Android](https://forum.xda-developers.com/general/general/root-stock-emoji-fonts-ios-windows10-t3418801).

**Comment by ltblueberry0** [comment]
Are there any plans to make this font compatible with iOS and macOS?

**Comment by dougfelt** [comment]
We have no plans to do that at this time.

**Comment by Crissov** [comment]
@vXBaKeRXv makes various [`.deb` packages](https://github.com/vXBaKeRXv/vxbakerxv.github.io/tree/master/repo/debs) with alternative `sbix` emoji fonts to be installed with Cydia on jailbroken iOS devices. This includes Noto as found on Android Nougat and Oreo.

**Comment by rsheeter** [comment]
This font uses https://docs.microsoft.com/en-us/typography/opentype/spec/cbdt; it will only work in environments that support that format. Until something like https://github.com/googlefonts/colr-gradients-spec/blob/master/colr-gradients-spec.md is broadly supported this will remain the case.

**Comment by canada11** [comment]
Following @Crissov's [response](https://github.com/googlefonts/noto-emoji/issues/72#issuecomment-343377828), someone wrote a Medium article how to do it: https://medium.com/@77belac77/how-to-get-googles-emoji-on-your-macbook-f99da72cf126, for others like me who still want this, quoting from the Medium article: 

> The Step-by-Step
> 1. Head over to this Github repo and download the .deb archive that contains your emoji set of choice.
> 2. Extract/open the .deb archive. Once inside, extract the archive named data.tar.gz. You’ll now see a folder called var. Inside that is a folder called mobile. Keep on going deeper and you’ll eventually reach your destination: a font file named AppleColorEmoji@2x.ttf.
> 3. Rename AppleColorEmoji@2x.ttf by putting spaces between each word and removing the ending, so that the new file name is Apple Color Emoji.ttf.
> 4. Keeping that Finder window open, start up Font Book (the built-in app where you can manage all the fonts installed on your device). In the left side panel at the top, select the ‘Computer’ option to show all the fonts you’ve installed as well as the default system fonts. If you scroll down the list of fonts, you should see an entry called Apple Color Emoji close to the bottom. This is the font file you’ll be overwriting, but don’t worry, this process is easily reversible!
> 5. Drag the Apple Color Emoji.ttf from the Finder window into Font Book. You’ll be prompted to install the font. It may warn you about it being a duplicate, but we already know that, so keep on going. Once you finish installing the new emoji font, you’re good to go! Try out your new emoji set by opening up your browser of choice, selecting a text field, and press CTRL+CMD+SPACEBAR to quickly bring up the emoji picker.

**Comment by 12people** [comment]
@canada11 Any way to get the latest version working?

**Comment by canada11** [comment]
Does this help?: https://apple.stackexchange.com/questions/248027/can-i-use-google-emoji-on-mac/409205#409205

**Comment by 12people** [comment]
@canada11 Not really — the emoji font recommended there is proprietary (the answer makes it sound as if it's open-source, but it actually isn't). I'm working on an open-source Flutter app and thus can't use this font there.

Thanks anyway, though.
