### ISSUE TITLE
Make dependencies explicit

### ISSUE THREAD

**Issue by brawer** [googlefonts/noto-emoji#8]
How about using [git submodules](https://www.kernel.org/pub/software/scm/git/docs/v1.6.1.3/git-submodule.html) for dependencies, in particular the exotic ones like fonttools and nototools?

Most of the other build dependencies can be figured out, but this one will be rather cryptic for people who build noto-emoji from source:

```
sascha@debian:~/src/noto-emoji$ make flags/CH.png
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 23, in <module>
    import add_emoji_gsub
  File "/home/sascha/src/noto-emoji/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
ImportError: No module named nototools
cd "/home/sascha/src/noto-emoji/third_party/pngquant" && make
make[1]: Entering directory '/home/sascha/src/noto-emoji/third_party/pngquant'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/sascha/src/noto-emoji/third_party/pngquant'
mkdir -p ./flags
./waveflag "third_party/region-flags/png/CH.png" "flags/CH.png"
Processing third_party/region-flags/png/CH.png
optipng -quiet -o7 "flags/CH.png"
"/home/sascha/src/noto-emoji/third_party/pngquant/pngquant" --speed 1 --skip-if-larger --ext '.png' --force "flags/CH.png"`
```

**Comment by brawer** [comment]
@behdad and @roozbehp, what do you think?

**Comment by roozbehp** [comment]
I haven't used git submodules, so I don't know how cumbersome/helpful they are.

At the very least, we should document the dependencies.

**Comment by Stephen304** [comment]
This would be great - I managed to get nototools installed but am stuck because of add_emoji_gsub. Git submodules would probably make it a lot easier for me to figure out where things are supposed to be.

**Comment by behdad** [comment]
I played with git submodules for noto.  Didn't like the fact that we'd need to roll forward the included module's hash all the time.  I couldn't find a way to hook it up to "master" and have it roll forward automatically.  If people can do that, that would help.

**Comment by brawer** [comment]
That might be intentional. If the version of a submodule (eg. noto-tools) could be rolled forward automatically, downstream projects (eg. noto-emoji) could not be built reproducibly anymore. From a release perspective, hermetic builds are usually considered a good thing.

**Comment by dougfelt** [comment]
Yeah, from what I read that was considered a feature of submodules, for
some uses.

It seems though that we could script a 'bring all submodules up to their
head' operation.

**Comment by behdad** [comment]
I understand.  I don't like the clutter it creates in the commit log.  But I can live with it if others do that.

**Comment by Stephen304** [comment]
It seems pretty typical to have bump submodule commits, so that seems
pretty standard practice.

**Comment by rsheeter** [comment]
Prereqs are documented on the root readme. Once you have a few basic tools the rest are acquired from PyPI.
